kind: pipeline
type: docker
name: test-pipeline

steps:
- name: greeting
  image: alpine
  commands:
  - touch test-output.txt
  - echo hello world! > test-output.txt

- name: build
  image: node:14.17.0
  commands:
  - npm install
  - export NODE_OPTIONS="--max-old-space-size=2048"
  - npm run build --prod

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: docker-hub-username
    password:
      from_secret: docker-hub-password
    repo: fjdrodrigues/rauma-social-dancing-web-app
